import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import { Rubik } from 'next/font/google';

const rubik = Rubik({
	weight: ['300', '400', '500', '700', '900'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${rubik.className} bg-accent-50`}>
				<div className="text-center py-2 text-xs font-bold">
					<span>
						Note: Due to postal delays, shipping is taking a bit longer than
						usual. International orders may also be delayed at your customs
						office. We appreciate your support and patience!
					</span>
				</div>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
